#pragma once

// grab from FurnaceBlockActor::FurnaceBlockActor
enum class BlockActorType {
  Furnace          = 0x01,
  Chest            = 0x02,
  NetherReactor    = 0x03,
  Sign             = 0x04,
  MobSpawner       = 0x05,
  Skull            = 0x06,
  FlowerPot        = 0x07,
  BrewingStand     = 0x08,
  EnchantingTable  = 0x09,
  DaylightDetector = 0x0A,
  Music            = 0x0B,
  Comparator       = 0x0C,
  Dispenser        = 0x0D,
  Dropper          = 0x0E,
  Hopper           = 0x0F,
  Cauldron         = 0x10,
  ItemFrame        = 0x11,
  Piston           = 0x12,
  Moving           = 0x13,
  Chalkboard       = 0x14,
  Beacon           = 0x15,
  EndPortal        = 0x16,
  EnderChest       = 0x17,
  EndGateway       = 0x18,
  ShulkerBox       = 0x19,
  CommandBlock     = 0x1A,
  Bed              = 0x1B,
  Banner           = 0x1C,

  Structure      = 0x20,
  Jukebox        = 0x21,
  ChemistryTable = 0x22,
  Conduit        = 0x23,
  Jigsaw         = 0x24,
  Lectern        = 0x25,
  BlastFurnace   = 0x26,
  Smoker         = 0x27,
  Bell           = 0x28,
  Campfire       = 0x29,
  Barrel         = 0x2A,
  Beehive        = 0x2B,
};