// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYER_MOD_PROTO_H_
#define FLATBUFFERS_GENERATED_PLAYER_MOD_PROTO_H_

#include "flatbuffers/flatbuffers.h"

#include "uuid_addition.h"
#include "uuid_generated.h"

namespace Mod {
namespace proto {

struct PlayerEntity;
struct PlayerEntityBuilder;
struct PlayerEntityT;

struct PlayerEventPacket;
struct PlayerEventPacketBuilder;
struct PlayerEventPacketT;

enum class PlayerEvent : uint8_t {
  NONE = 0,
  joined = 1,
  left = 2,
  MIN = NONE,
  MAX = left
};

inline const PlayerEvent (&EnumValuesPlayerEvent())[3] {
  static const PlayerEvent values[] = {
    PlayerEvent::NONE,
    PlayerEvent::joined,
    PlayerEvent::left
  };
  return values;
}

inline const char * const *EnumNamesPlayerEvent() {
  static const char * const names[4] = {
    "NONE",
    "joined",
    "left",
    nullptr
  };
  return names;
}

inline const char *EnumNamePlayerEvent(PlayerEvent e) {
  if (flatbuffers::IsOutRange(e, PlayerEvent::NONE, PlayerEvent::left)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPlayerEvent()[index];
}

struct PlayerEventUnion {
  PlayerEvent type;
  void *value;

  PlayerEventUnion() : type(PlayerEvent::NONE), value(nullptr) {}
  PlayerEventUnion(PlayerEventUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(PlayerEvent::NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  PlayerEventUnion(const PlayerEventUnion &);
  PlayerEventUnion &operator=(const PlayerEventUnion &u)
    { PlayerEventUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  PlayerEventUnion &operator=(PlayerEventUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~PlayerEventUnion() { Reset(); }

  void Reset();

  static void *UnPack(const void *obj, PlayerEvent type, const flatbuffers::resolver_function_t *resolver);
  flatbuffers::Offset<void> Pack(flatbuffers::FlatBufferBuilder &_fbb, const flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  Mod::proto::PlayerEntityT *Asjoined() {
    return type == PlayerEvent::joined ?
      reinterpret_cast<Mod::proto::PlayerEntityT *>(value) : nullptr;
  }
  const Mod::proto::PlayerEntityT *Asjoined() const {
    return type == PlayerEvent::joined ?
      reinterpret_cast<const Mod::proto::PlayerEntityT *>(value) : nullptr;
  }
  Mod::proto::PlayerEntityT *Asleft() {
    return type == PlayerEvent::left ?
      reinterpret_cast<Mod::proto::PlayerEntityT *>(value) : nullptr;
  }
  const Mod::proto::PlayerEntityT *Asleft() const {
    return type == PlayerEvent::left ?
      reinterpret_cast<const Mod::proto::PlayerEntityT *>(value) : nullptr;
  }
};

bool VerifyPlayerEvent(flatbuffers::Verifier &verifier, const void *obj, PlayerEvent type);
bool VerifyPlayerEventVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

struct PlayerEntityT : public flatbuffers::NativeTable {
  typedef PlayerEntity TableType;
  std::string name;
  uint64_t xuid;
  mce::UUID uuid;
  std::string address;
  PlayerEntityT()
      : xuid(0) {
  }
};

struct PlayerEntity FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PlayerEntityT NativeTableType;
  typedef PlayerEntityBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_XUID = 6,
    VT_UUID = 8,
    VT_ADDRESS = 10
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  uint64_t xuid() const {
    return GetField<uint64_t>(VT_XUID, 0);
  }
  const Mod::proto::UUID *uuid() const {
    return GetStruct<const Mod::proto::UUID *>(VT_UUID);
  }
  const flatbuffers::String *address() const {
    return GetPointer<const flatbuffers::String *>(VT_ADDRESS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint64_t>(verifier, VT_XUID) &&
           VerifyField<Mod::proto::UUID>(verifier, VT_UUID) &&
           VerifyOffset(verifier, VT_ADDRESS) &&
           verifier.VerifyString(address()) &&
           verifier.EndTable();
  }
  PlayerEntityT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PlayerEntityT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<PlayerEntity> Pack(flatbuffers::FlatBufferBuilder &_fbb, const PlayerEntityT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PlayerEntityBuilder {
  typedef PlayerEntity Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(PlayerEntity::VT_NAME, name);
  }
  void add_xuid(uint64_t xuid) {
    fbb_.AddElement<uint64_t>(PlayerEntity::VT_XUID, xuid, 0);
  }
  void add_uuid(const Mod::proto::UUID *uuid) {
    fbb_.AddStruct(PlayerEntity::VT_UUID, uuid);
  }
  void add_address(flatbuffers::Offset<flatbuffers::String> address) {
    fbb_.AddOffset(PlayerEntity::VT_ADDRESS, address);
  }
  explicit PlayerEntityBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  PlayerEntityBuilder &operator=(const PlayerEntityBuilder &);
  flatbuffers::Offset<PlayerEntity> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PlayerEntity>(end);
    return o;
  }
};

inline flatbuffers::Offset<PlayerEntity> CreatePlayerEntity(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    uint64_t xuid = 0,
    const Mod::proto::UUID *uuid = 0,
    flatbuffers::Offset<flatbuffers::String> address = 0) {
  PlayerEntityBuilder builder_(_fbb);
  builder_.add_xuid(xuid);
  builder_.add_address(address);
  builder_.add_uuid(uuid);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<PlayerEntity> CreatePlayerEntityDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    uint64_t xuid = 0,
    const Mod::proto::UUID *uuid = 0,
    const char *address = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto address__ = address ? _fbb.CreateString(address) : 0;
  return Mod::proto::CreatePlayerEntity(
      _fbb,
      name__,
      xuid,
      uuid,
      address__);
}

flatbuffers::Offset<PlayerEntity> CreatePlayerEntity(flatbuffers::FlatBufferBuilder &_fbb, const PlayerEntityT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PlayerEventPacketT : public flatbuffers::NativeTable {
  typedef PlayerEventPacket TableType;
  Mod::proto::PlayerEventUnion event;
  PlayerEventPacketT() {
  }
};

struct PlayerEventPacket FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PlayerEventPacketT NativeTableType;
  typedef PlayerEventPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EVENT_TYPE = 4,
    VT_EVENT = 6
  };
  Mod::proto::PlayerEvent event_type() const {
    return static_cast<Mod::proto::PlayerEvent>(GetField<uint8_t>(VT_EVENT_TYPE, 0));
  }
  const void *event() const {
    return GetPointer<const void *>(VT_EVENT);
  }
  const Mod::proto::PlayerEntity *event_as_joined() const {
    return event_type() == Mod::proto::PlayerEvent::joined ? static_cast<const Mod::proto::PlayerEntity *>(event()) : nullptr;
  }
  const Mod::proto::PlayerEntity *event_as_left() const {
    return event_type() == Mod::proto::PlayerEvent::left ? static_cast<const Mod::proto::PlayerEntity *>(event()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_EVENT_TYPE) &&
           VerifyOffset(verifier, VT_EVENT) &&
           VerifyPlayerEvent(verifier, event(), event_type()) &&
           verifier.EndTable();
  }
  PlayerEventPacketT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PlayerEventPacketT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<PlayerEventPacket> Pack(flatbuffers::FlatBufferBuilder &_fbb, const PlayerEventPacketT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PlayerEventPacketBuilder {
  typedef PlayerEventPacket Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_event_type(Mod::proto::PlayerEvent event_type) {
    fbb_.AddElement<uint8_t>(PlayerEventPacket::VT_EVENT_TYPE, static_cast<uint8_t>(event_type), 0);
  }
  void add_event(flatbuffers::Offset<void> event) {
    fbb_.AddOffset(PlayerEventPacket::VT_EVENT, event);
  }
  explicit PlayerEventPacketBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  PlayerEventPacketBuilder &operator=(const PlayerEventPacketBuilder &);
  flatbuffers::Offset<PlayerEventPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PlayerEventPacket>(end);
    return o;
  }
};

inline flatbuffers::Offset<PlayerEventPacket> CreatePlayerEventPacket(
    flatbuffers::FlatBufferBuilder &_fbb,
    Mod::proto::PlayerEvent event_type = Mod::proto::PlayerEvent::NONE,
    flatbuffers::Offset<void> event = 0) {
  PlayerEventPacketBuilder builder_(_fbb);
  builder_.add_event(event);
  builder_.add_event_type(event_type);
  return builder_.Finish();
}

flatbuffers::Offset<PlayerEventPacket> CreatePlayerEventPacket(flatbuffers::FlatBufferBuilder &_fbb, const PlayerEventPacketT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline PlayerEntityT *PlayerEntity::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<Mod::proto::PlayerEntityT> _o = std::unique_ptr<Mod::proto::PlayerEntityT>(new PlayerEntityT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PlayerEntity::UnPackTo(PlayerEntityT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = xuid(); _o->xuid = _e; }
  { auto _e = uuid(); if (_e) _o->uuid = flatbuffers::UnPack(*_e); }
  { auto _e = address(); if (_e) _o->address = _e->str(); }
}

inline flatbuffers::Offset<PlayerEntity> PlayerEntity::Pack(flatbuffers::FlatBufferBuilder &_fbb, const PlayerEntityT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePlayerEntity(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<PlayerEntity> CreatePlayerEntity(flatbuffers::FlatBufferBuilder &_fbb, const PlayerEntityT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const PlayerEntityT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _xuid = _o->xuid;
  auto _uuid = flatbuffers::Pack(_o->uuid);
  auto _address = _o->address.empty() ? 0 : _fbb.CreateString(_o->address);
  return Mod::proto::CreatePlayerEntity(
      _fbb,
      _name,
      _xuid,
      &_uuid,
      _address);
}

inline PlayerEventPacketT *PlayerEventPacket::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<Mod::proto::PlayerEventPacketT> _o = std::unique_ptr<Mod::proto::PlayerEventPacketT>(new PlayerEventPacketT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PlayerEventPacket::UnPackTo(PlayerEventPacketT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = event_type(); _o->event.type = _e; }
  { auto _e = event(); if (_e) _o->event.value = Mod::proto::PlayerEventUnion::UnPack(_e, event_type(), _resolver); }
}

inline flatbuffers::Offset<PlayerEventPacket> PlayerEventPacket::Pack(flatbuffers::FlatBufferBuilder &_fbb, const PlayerEventPacketT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePlayerEventPacket(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<PlayerEventPacket> CreatePlayerEventPacket(flatbuffers::FlatBufferBuilder &_fbb, const PlayerEventPacketT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const PlayerEventPacketT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _event_type = _o->event.type;
  auto _event = _o->event.Pack(_fbb);
  return Mod::proto::CreatePlayerEventPacket(
      _fbb,
      _event_type,
      _event);
}

inline bool VerifyPlayerEvent(flatbuffers::Verifier &verifier, const void *obj, PlayerEvent type) {
  switch (type) {
    case PlayerEvent::NONE: {
      return true;
    }
    case PlayerEvent::joined: {
      auto ptr = reinterpret_cast<const Mod::proto::PlayerEntity *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case PlayerEvent::left: {
      auto ptr = reinterpret_cast<const Mod::proto::PlayerEntity *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPlayerEventVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPlayerEvent(
        verifier,  values->Get(i), types->GetEnum<PlayerEvent>(i))) {
      return false;
    }
  }
  return true;
}

inline void *PlayerEventUnion::UnPack(const void *obj, PlayerEvent type, const flatbuffers::resolver_function_t *resolver) {
  switch (type) {
    case PlayerEvent::joined: {
      auto ptr = reinterpret_cast<const Mod::proto::PlayerEntity *>(obj);
      return ptr->UnPack(resolver);
    }
    case PlayerEvent::left: {
      auto ptr = reinterpret_cast<const Mod::proto::PlayerEntity *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline flatbuffers::Offset<void> PlayerEventUnion::Pack(flatbuffers::FlatBufferBuilder &_fbb, const flatbuffers::rehasher_function_t *_rehasher) const {
  switch (type) {
    case PlayerEvent::joined: {
      auto ptr = reinterpret_cast<const Mod::proto::PlayerEntityT *>(value);
      return CreatePlayerEntity(_fbb, ptr, _rehasher).Union();
    }
    case PlayerEvent::left: {
      auto ptr = reinterpret_cast<const Mod::proto::PlayerEntityT *>(value);
      return CreatePlayerEntity(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline PlayerEventUnion::PlayerEventUnion(const PlayerEventUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case PlayerEvent::joined: {
      value = new Mod::proto::PlayerEntityT(*reinterpret_cast<Mod::proto::PlayerEntityT *>(u.value));
      break;
    }
    case PlayerEvent::left: {
      value = new Mod::proto::PlayerEntityT(*reinterpret_cast<Mod::proto::PlayerEntityT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void PlayerEventUnion::Reset() {
  switch (type) {
    case PlayerEvent::joined: {
      auto ptr = reinterpret_cast<Mod::proto::PlayerEntityT *>(value);
      delete ptr;
      break;
    }
    case PlayerEvent::left: {
      auto ptr = reinterpret_cast<Mod::proto::PlayerEntityT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = PlayerEvent::NONE;
}

}  // namespace proto
}  // namespace Mod

#endif  // FLATBUFFERS_GENERATED_PLAYER_MOD_PROTO_H_
